NaiNaiNai17/echoTix

README.md
=> first New Commit

README.md
=> changed readme title

frontend/README.md, frontend/src/wrapper/Wrapper.js
=> added GNU license, backend file and some dependencies

LICENSE, package-lock.json, package.json, server.js
committed server and package JSON changes
=> edited package JSON  and added server file

README.md
fixed the path for editing logo
=> logo edit path

frontend/public/index.html, frontend/src/App.jsx
=> added google.fonts in html, style in html and changed App.js -> App.jsx

frontend/src/App.jsx, frontend/src/components/Navbar/Navbar.jsx, frontend/src/components/styles/Navbar.styled.js, frontend/src/hoc/MainRouter.jsx, frontend/src/pages/Home/Home.jsx
=> started to set-up styled-components and general things

frontend/package-lock.json, frontend/package.json, frontend/src/components/Navbar/Navbar.jsx, frontend/src/components/styles/Navbar.styled.js
Now we have real classes for better designing and i added a badge to the shopping card!
=> clases for devtools, shopping-cart-badge

controller/ticketController.js
Api info parsed well in backed. Still need prices.
=> api added to backend, info parsed well except prices

frontend/src/components/Cards/Card.jsx, frontend/src/components/Cards/Cards.jsx, frontend/src/components/styles/Card.styled.js, frontend/src/components/styles/Cards.styled.js, frontend/src/data.js, frontend/src/pages/Home/Home.jsx
I made the squares section... let's check it out!
=> square component set up

controller/ticketController.js
Parsed only data we need from backend
=> parse only data we need from api

frontend/package-lock.json, frontend/package.json, frontend/src/components/Footer/Footer.jsx, frontend/src/components/styles/Footer.styled.js, frontend/src/pages/Home/Home.jsx
Hey hey, it's getting. Forward. Footer Set Up is made!
=> footer set-up

controller/ticketController.js, controller/userController.js, models/UserSchema.js, routes/ticketRoutes.js, routes/userRoutes.js, server.js
Check out the routes and controller for user. Just need to edit roles and role auth
=> added user routes and controller. Needs roles and authorization

controller/ticketController.js
Hey Lars, we now have the prices from the api in the data array. The prices object is big so still needs interating to parse just some info. Will continue.
=> data array now includes prices array

frontend/package-lock.json, frontend/package.json, frontend/src/components/CheckoutComponent/CheckoutComponent.jsx, frontend/src/components/styles/Checkout.styled.js, frontend/src/hoc/MainRouter.jsx
Here we go with the CheckoutComponent SetUp. 
DO NOT DELETE BRANCH
:-D
=> Checkout component

controller/ticketController.js, routes/ticketRoutes.js
Still working on the search function, but api pulls correct price info.  Endpoint for search added
=> search controller still needs work, endpoint added

frontend/src/components/Modal/Login.jsx, frontend/src/components/styles/RegisterLogin.js
installed the Register-Button on Login
=> register button on login

frontend/src/hoc/MainRouter.jsx, frontend/src/pages/Checkout/Checkout.jsx
Not Routing changed here, just deleted Navbar and Footer on Checkout. DELETE BRANCH!
=> Deleted Navbar and Footer on Checkout

frontend/src/components/Modal/Login.jsx, frontend/src/components/Register/Register.jsx, frontend/src/components/styles/RegisterLogin.js, frontend/src/pages/Register/Register.jsx
I fixed the Login Modal, and changed buttoncotainer ot buttoncontainer! DELETE BRANCH
=> fixed the login and register

frontend/src/components/Modal/Login.jsx, frontend/src/components/Navbar/Navbar.jsx, frontend/src/components/styles/Navbar.styled.js
I tired to make the ternary work, but unfortunately it didn't worked out. There is one little peace missing. Beside that i styled the navbar with the logout button. Now The Tree-Area has a width of 60% and the UserIcons have 40%... I flexed it and centered the Icons with align-items. DELETE BRANCH!
=> setup ternary-operator and stayled the navbar with logout icon

frontend/src/components/styles/NoShows.styled.js, frontend/src/components/styles/NoShowsNotFound.styled.js, frontend/src/hoc/MainRouter.jsx, frontend/src/pages/NoShows/NoShows.jsx, frontend/src/pages/NotFound/NotFound.jsx
Set Up the Now Show Page! DELETE BRANCH!
=> noshowpage setup Done

frontend/src/App.css, frontend/src/assets/scss/main.scss, frontend/src/components/BuyTickets/EventInfo.jsx, frontend/src/components/Evaluation/Evaluation.jsx, frontend/src/components/Evaluation/FinancialEvaluation.jsx, frontend/src/components/Evaluation/GeneralEvaluation.jsx, frontend/src/components/styles/BuyTickets.styled.js, frontend/src/components/styles/Cards.styled.js, frontend/src/components/styles/Counter.styled.js, frontend/src/components/styles/Evaluation.styled.js, frontend/src/components/styles/HeadlineBoxes/EvaluationHeaderBoxes.styled.js, frontend/src/components/styles/Navbar.styled.js, frontend/src/components/styles/Subhero.styled.js, frontend/src/data.js, frontend/src/hoc/MainRouter.jsx, frontend/src/pages/Admin/AdminView.jsx, frontend/src/pages/BuyTickets/BuyTickets.jsx
Here i touched the navbar and deleted (commented out) the background as i did for the whole page. The whole background of the page has now linear background.
=> the whole page is linear gradient-green

frontend/src/components/Cards/Cards.jsx, frontend/src/components/Navbar/Navbar.jsx, frontend/src/components/styles/Navbar.styled.js, frontend/src/util/axiosInstance.js
=> search works

frontend/src/assets/scss/main.scss, frontend/src/components/Buttons/Buy.jsx, frontend/src/components/BuyTickets/Counter.jsx, frontend/src/components/BuyTickets/EventData.jsx, frontend/src/components/styles/Buttons/Buy.styled.js, frontend/src/components/styles/Hero.styled.js, frontend/src/hoc/MainRouter.jsx
The Buy-Button is now linking to shopping-cart!
=> navigate works

controller/basketController.js, controller/ticketController.js, frontend/src/components/CheckoutComponent/CheckoutComponent.jsx, frontend/src/components/Navbar/Navbar.jsx, models/BasketSchema.js, models/ProductSchema.js, routes/basketRoutes.js, routes/ticketRoutes.js, routes/userRoutes.js, server.js
Basket schema and partial order controller. Will add a ticket model and controller separately. Do Not Delete Branch!
=> basket schema and partial controller order finished

controller/ticketController.js, frontend/src/components/BuyTickets/EventInfo.jsx, frontend/src/components/Cards/Card.jsx, frontend/src/components/Cards/Events.jsx, frontend/src/components/Register/Register.jsx, frontend/src/pages/SearchResults/SearchResults.jsx, routes/ticketRoutes.js
Success in fixing search results and current shows listed and added prices to tickets
=> fixed search results and added prices

frontend/src/components/Buttons/Shows.jsx, frontend/src/components/Cards/Card.jsx, frontend/src/components/Cards/DefaultCard.jsx, frontend/src/components/styles/Buttons/Tickets.styled.js, frontend/src/components/styles/Card.styled.js, frontend/src/components/styles/DefaultCard.styled.js, frontend/src/data.js
=> Data file date setup

frontend/src/assets/scripts/navbar.js, frontend/src/assets/scss/main.scss, frontend/src/components/Navbar/Navbar.jsx, frontend/src/components/styles/Navbar.styled.js
Now we have a sticky navbar. I don't know if we want this :D I can build something, where the Navbar disappear and when scrolling it's there... but for now. Thats it
=> Stickynavbar

frontend/src/components/Buttons/Buy.jsx, frontend/src/components/BuyTickets/Counter.jsx, frontend/src/components/BuyTickets/EventInfo.jsx, frontend/src/components/CheckoutComponent/CheckoutComponent.jsx, frontend/src/components/Navbar/Navbar.jsx, frontend/src/components/styles/Navbar.styled.js
I added the basket function and could use some changes to style we can fix together. Also remembering I commented the sticky navbar out for presentation.
=> added basket function

frontend/package-lock.json, frontend/package.json, frontend/src/assets/scss/main.scss, frontend/src/components/CheckoutComponent/CheckoutComponent.jsx, frontend/src/components/Navbar/Navbar.jsx, frontend/src/components/styles/Checkout.styled.js, frontend/src/components/styles/Footer.styled.js, frontend/src/components/styles/Navbar.styled.js, frontend/src/components/styles/RegisterLogin.js, frontend/src/hoc/MainRouter.jsx, frontend/src/pages/Login/Login.jsx, frontend/src/responsive.js
there we go... last round design-shaping :D
=> Login mobile

frontend/src/components/Buttons/Buy.jsx, frontend/src/components/BuyTickets/Counter.jsx, frontend/src/components/BuyTickets/EventInfo.jsx
=> added city to buy page

frontend/src/components/CheckoutComponent/CheckoutComponent.jsx, frontend/src/components/styles/Checkout.styled.js, frontend/src/components/styles/Navbar.styled.js
=> all looks okay
